### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by Noe333SC** [SistemasTecTlaxiaco/actividad-1-infografia-Noe333SC#2]
[Infografia cliclos de vida del software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Noe333SC/files/9428343/Infografia.cliclos.de.vida.del.software.pdf)

**Comment by Valentiin01** [comment]
Calificación 18.5 se recomienda que sea en 1 o 2 hojas.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
